### ISSUE TITLE
SomeProblem

### ISSUE THREAD

**Issue by oit63** [MP0w/MPParallaxCollection#1]
After 'pod install' in directory 'Example'
it says: 
Unable to find a specification for `MPTextReveal`
Help

---

$ pod install
Analyzing dependencies
Fetching podspec for `MPParallaxCollection` from `../`
[!] Unable to find a specification for `MPTextReveal`

**Comment by MP0w** [comment]
Sorry the specs are probably wrong... this pod is unfortunately not maintained ATM
